### ISSUE TITLE
Content to be provided

### ISSUE THREAD

**Issue by daanyal-rahila-memon** [GDGCloudLahore/Build-With-AI#5]
- Speakers' information
- discord link
- RSVP git link
any other important content you want to update over the site

**Comment by adilshehzad786** [comment]
Labs Link : https://github.com/GDGCloudLahore/Build-With-AI-Labs-Google-Gemini

**Comment by adilshehzad786** [comment]
Instagram :https://www.instagram.com/cloudlahoregdg/
Linkedin : https://www.linkedin.com/company/gdgcloudlahore/

We are not using fb as regular so good to remove and discord link is already provided
